### ISSUE TITLE
Issue with dynamic data Image Showing coming form Api 

### ISSUE THREAD

**Issue by Deep-CB** [KPS250/React-Native-FlatList-Slider#11]
Indicators are showing according to the count of array and sometimes images are showing and sometimes not after reloading these are not showing and Not taking any space for image because if the image is taking time for load then images will take a height for image in rendered view but this was not taking any image space
<FlatListSlider
data={featuredData}
timer={5000}
component={}
onPress={(item) => alert(JSON.stringify(item))}
indicatorContainerStyle={{
position: 'absolute',
bottom: 20,
right: 20,
}}
indicatorActiveColor={'#FFFFFF'}
indicatorInActiveColor={'grey'}
indicatorActiveWidth={20}
autoscroll={false}
animation={false}
/>

import React from 'react';
import {
View,
Text,
TouchableOpacity,
Image,
StyleSheet,
Platform,
Dimensions,
} from 'react-native';

const screenWidth = Math.round(Dimensions.get('window').width);
export default Preview = ({
style,
item,
imageKey,
onPress,
index,
active,
local,
}) => {
return (
<TouchableOpacity
style={styles.videoContainer}
onPress={() => onPress(item)}>
<View style={[styles.imageContainer, styles.shadow]}>
<Image
style={[styles.videoPreview, active ? {} : {height: 300}]}
source={{uri: item[imageKey]}}
resizeMode="cover"
/>
</TouchableOpacity>
);
};

const styles = StyleSheet.create({
videoContainer: {
width: screenWidth,
// paddingVertical: 28,
justifyContent: 'center',
alignItems: 'center',
// marginRight: 20,
},
videoPreview: {
width: screenWidth,
height: 300,
borderBottomLeftRadius: 15,
borderBottomRightRadius: 15,
resizeMode: 'contain',
},
desc: {
fontSize: 14,
letterSpacing: 0,
lineHeight: 24,
marginTop: 18,
},
imageContainer: {
justifyContent: 'center',
alignItems: 'center',
width: screenWidth,
},
shadow: {
...Platform.select({
ios: {
shadowColor: 'black',
shadowOffset: {width: 0, height: 1},
shadowOpacity: 0.1,
shadowRadius: 5,
},
android: {
elevation: 5,
},
}),
},
});

**Comment by sajas-nm** [comment]
try it with  pass default style prop to custom image component 

 ` <Image
        style={[styles.image, style, {height: height}]}
        source={local ? item[imageKey] : {uri: item[imageKey]}}
      />`

**Comment by jjpeeradech** [comment]
{featuredData.length>0?< FlatListSlider />:<></>} here this is workaround
