### ISSUE TITLE
npm install NOT working

### ISSUE THREAD

**Issue by sisoalbert** [KPS250/React-Native-FlatList-Slider#15]
Error below:
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Users\user-pc\code\AwesomeProject\node_modules\acorn
npm ERR! dest C:\Users\user-pc\code\AwesomeProject\node_modules\.acorn-syArxInz
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\user-pc\code\AwesomeProject\node_modules\acorn' -> 'C:\Users\user-pc\code\AwesomeProject\node_modules\.acorn-syArxInz'
npm ERR!  [Error: EPERM: operation not permitted, rename 'C:\Users\user-pc\code\AwesomeProject\node_modules\acorn' -> 'C:\Users\user-pc\code\AwesomeProject\node_modules\.acorn-syArxInz'] {
npm ERR!   errno: -4048,
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\user-pc\\code\\AwesomeProject\\node_modules\\acorn',
npm ERR!   dest: 'C:\\Users\\user-pc\\code\\AwesomeProject\\node_modules\\.acorn-syArxInz'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user-pc\AppData\Local\npm-cache\_logs\2021-01-20T18_02_30_808Z-debug.log

yarn add seems to be working

**Comment by KPS250** [comment]
Checked and didn't face any issue for npm install.
