### ISSUE TITLE
ReferenceError: Can't find variable: Indicator

### ISSUE THREAD

**Issue by jorge-o-murillo** [KPS250/React-Native-FlatList-Slider#18]
Thanks for the work on the component.

I'm on React Native v0.63.2 and running the component out of the box greets me with this error:

> ReferenceError: Can't find variable: Indicator
> ReferenceError: Can't find variable: ChildItem

I made the following changes to each respective file and got it to work:
```
const Indicator = ({
  itemCount,
  currentIndex,
  indicatorStyle,
  indicatorContainerStyle,
  indicatorActiveColor,
  indicatorInActiveColor,
  indicatorActiveWidth = 6,
}) => {
  return (
    <View style={[styles.container, indicatorContainerStyle]}>
      {renderIndicator(
        itemCount,
        currentIndex,
        indicatorStyle,
        indicatorActiveColor,
        indicatorInActiveColor,
        indicatorActiveWidth,
      )}
    </View>
  );
};

export default Indicator;
```

I wonder if other users have this issue as well.

**Comment by kommandantee** [comment]
I re-run the project with "npx react-native run-android" after this component installation and it solved.
