### ISSUE TITLE
Missing index.d.ts: TypeScript error

### ISSUE THREAD

**Issue by asalha** [KPS250/React-Native-FlatList-Slider#22]
Could not find a declaration file for module 'react-native-flatlist-slider'. 'd:/github/PROJECT-NAME/node_modules/react-native-flatlist-slider/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-flatlist-slider` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-flatlist-slider';`ts(7016)

**Comment by KPS250** [comment]
The library isn't written with TS support. Will get it ported to TS in near future.
