### ISSUE TITLE
Add new prop removeClippedSubviews

### ISSUE THREAD

**Issue by JoshuaC817** [KPS250/React-Native-FlatList-Slider#24]
Flat list sometimes are not rendered properly when implemented in tabview, refer to issue below

https://github.com/meliorence/react-native-snap-carousel/issues/238

So due to this issue, is it possible to add in removeClippedSubviews as one of the props for us to temporary resolve this?

Thanks!

**Comment by KPS250** [comment]
@WLeo8 its been added in the latest release V1.0.6.
