### ISSUE TITLE
ERROR TypeError: undefined is not an object (evaluating 'config.duration')

### ISSUE THREAD

**Issue by raikk** [KPS250/React-Native-FlatList-Slider#25]
i installed it using yarn and i am getting this error
`undefined is not an object (evaluating 'config.duration')`

**Comment by bahmanworld** [comment]
> i installed it using yarn and i am getting this error
> `undefined is not an object (evaluating 'config.duration')`

- Same error, what is the problem?

I'm using `React Native 0.65`
`Error comes from LayoutAnimation`

**Comment by parmarravi** [comment]
same error. any solution

**Comment by sufyanuchiha** [comment]
> i installed it using yarn and i am getting this error
> `undefined is not an object (evaluating 'config.duration')`

Having same problem!!!

**Comment by KPS250** [comment]
You can set  prop animation={false} to temporarily fix it. Meanwhile I will look into it.

**Comment by KPS250** [comment]
Have pushed V1.0.6 with the fix. You can test it.

**Comment by ymys** [comment]
Tried newest but still facing same error. Any solution for this?

![image](https://user-images.githubusercontent.com/3107838/183031088-149b8c8c-0406-46cd-b28e-85fd505645ad.png)

Update: Temporarily solved by commenting this at FlatListSlider.js:
    // if (this.props.animation) {
    //   LayoutAnimation.configureNext(LayoutAnimation.Presets.spring);
    // }
