### ISSUE TITLE
Key property on the View in 'Indicator' Component

### ISSUE THREAD

**Issue by augini** [KPS250/React-Native-FlatList-Slider#5]
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Indicator`. See https://fb.me/react-warning-keys for more information.

Hello. 
First of all the library is amazing and thanks for providing it. 

However, the missing key property on the view in Indicator component is throwing that error. I am fixing everytime when I run 'npm install'.

I would appreciate if you could fix it. 

Thanks

**Comment by KPS250** [comment]
I just merged your PR. Will soon publish a new version on NPM.
