### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by 4cc3ssX** [KPS250/React-Native-FlatList-Slider#7]
### Indicator Warning
When run module with Indicator, following warning reveal in react native

> Warning: Each child in a list should have a unique "key" prop.

> Check the render method of `Indicator`. See https://fb.me/react-warning-keys for more information.
>    in View (at Indicator.js:38)
>    in Indicator (at FlatListSlider.js:115)
>    in RCTView (at View.js:34)
>    in View (at FlatListSlider.js:75)
>    in FlatListSlider (at Zoom.js:34)

![Capture](https://user-images.githubusercontent.com/57473799/96552942-7761ca00-12da-11eb-8296-bd5194a81c65.PNG)

### Step to reproduce 

It's pretty easy. Go to the module path node_modules/react-native-flatlist-slider/src and edit at `<View>` and add `key={i}` in Indicator.js

![Capture1](https://user-images.githubusercontent.com/57473799/96552963-7cbf1480-12da-11eb-9307-cc779bc3ebd5.PNG)

**Comment by gjungic** [comment]
I have the same problem.

**Comment by augini** [comment]
Hello Guys .
As far as I am concerned, this issue has been fixed since I created a pull request for this issue and the author merged it. However if you are still having this problem with the latest version, add key ={i.toString()} to the view in indicator.js

**Comment by gjungic** [comment]
> Hello Guys .
> As far as I am concerned, this issue has been fixed since I created a pull request for this issue and the author merged it. However if you are still having this problem with the latest version, add key ={i.toString()} to the view in indicator.js

Probably it's not released yet. The latest npm version is `1.0.4` without `key` in `Indicator.js`.

**Comment by 4cc3ssX** [comment]
Ok. so I'll close this issue.
