### ISSUE TITLE
Image is not showing.

### ISSUE THREAD

**Issue by akshaykumar0291** [KPS250/React-Native-FlatList-Slider#9]
Hi, I have just followed your code and trying to create a component. All setup is done but at last, the image is not showing.

**Comment by KPS250** [comment]
> Hi, I have just followed your code and trying to create a component. All setup is done but at last, the image is not showing.

@akshaykumar0291 can you provide your code  so that I can help you with your issue?

**Comment by KPS250** [comment]
@akshaykumar0291 assuming this is fixed from your end. Closing the issue.
